<?php

/**
 * Load the theme default header to before loading Users
 *
 * @author      ThemeXenia
 * @copyright   Acme (c) 2019
 * @version     1.0.0
 * @link        https://acme.app
 * @since       1.0.0
 * @package     Auth
 * @subpackage  Users
 */

// NOTE: Do not edit this file

// Path to the template file
$viewPath = 'Acme/Layouts/Themes/' . $theme . '/Headers/header_0';

// Path to the view hooks file
$viewHooksPath = 'Acme/System/Modules/Auth/Users/Views/Hooks/';

// Checks whether the page actually exists.
// PHP’s native is_file() function is used to check whether the file is where it’s expected to be.
// The PageNotFoundException is a CodeIgniter exception that causes the default error page to show.
if ( ! is_file(ROOTPATH . $viewPath . '.php'))
{

    ob_get_clean();

    //Clean (erase) the output buffer and turn off output buffering
    ob_end_clean();

    // Whoops, we don't have a page for that!
    throw new \CodeIgniter\Exceptions\PageNotFoundException($viewPath);

}else{

    // Adjust the path so that the view parser can locate our template
    $layoutFile = '../../' . $viewPath;

    // Adjust the path so that the view parser can locate our view hooks
    $hooksPath = '../../' . $viewHooksPath;

    // Get views from hooks

    // Get the content to display immediately after the <head> open tag
    $contentAfterHeadOpen = view($hooksPath . "UsersHeadAfterOpen");
    // Get the user custom styles for this specific module
    $contentCustomStyles = view($hooksPath . "UsersCustomStyles");
    // Get the content to display immediately before the <head> close tag
    $contentBeforeHeadClose = view($hooksPath . "UsersHeadBeforeClose");
    // Get the content to display immediately after the <body> open tag
    $contentAfterBodyOpen = view( $hooksPath . "UsersBodyAfterOpen");

    // Consolidate the views
    $viewData = array(
        "contentAfterHeadOpen" => $contentAfterHeadOpen,
        "contentCustomStyles" => $contentCustomStyles,
        "contentBeforeHeadClose" => $contentBeforeHeadClose,
        "contentAfterBodyOpen" => $contentAfterBodyOpen
    );

    // Render the moduletemplate :: modulecomponent layout
    echo view($layoutFile, $viewData);

}

?>

