<?php

/**
 * Content layout view for the Dashboard
 *
 * @author      ThemeXenia
 * @copyright   Acme (c) 2019
 * @version     1.0.0
 * @link        https://acme.app
 * @since       1.0.0
 * @package     Admin
 * @subpackage  Dashboard
 */

// Override config value by user params
if($params){
    
    foreach ($params as $param_key=>$param_value){
        
        $config[$param_key] = $param_value;
        
    }
    
}

// NOTE: Do not edit this file

// Path to the template file
$viewPath = 'Acme/Modules/Dashboard/Views/Themes/' . $theme . '/' . $layout;

// Checks whether the page actually exists.
// PHP’s native is_file() function is used to check whether the file is where it’s expected to be.
// The PageNotFoundException is a CodeIgniter exception that causes the default error page to show.
if ( ! is_file(ROOTPATH . $viewPath . '.php'))
{

    // Clear our previously rendered output
    ob_get_clean();

    //Clean (erase) the output buffer and turn off output buffering
    ob_end_clean();

    // Whoops, we don't have a page for that!
    throw new \CodeIgniter\Exceptions\PageNotFoundException($viewPath);

}else{

    // Adjust the path so that the view parser can locate our template
    $layoutFile = '../../' . $viewPath;

    // Render the auth :: users layout
    echo view($layoutFile);

}

?>
