<?php

/**
 * Base Controller Class Users
 *
 * @author      ThemeXenia
 * @copyright   Acme (c) 2019
 * @version     1.0.0
 * @link        https://acme.app
 * @since       1.0.0
 * @package     Auth
 * @subpackage  Users
 */

namespace Acme\Core\System\Modules\Auth\Users\Controllers;

if (!defined('ACME_NAMESPACE')) ACME_exception(null, 'The application namespace is undefined. Please check your installation');

// Note: Do not edit this file

class RolesBaseController extends \Acme\Core\Bases\AcmeController
{

    /**
     * The array to hold the Users config values
     *
     * @var array $params
     */
    public $params;

    /**
     * Use this to check the health status of this module
     * @var string $healthCheckName
     */
    public $healthCheckName;

    /**
     * The component model class
     *
     * @var class $usersModel
     */
    public $usersModel;

    /**
     * Initialize the configurations for the users
     *
     * @param class $usersConfig
     */
    public $usersConfig;

    /**
     * Initialize the libraries for the users
     *
     * @var class $usersLibrary
     */
    public $usersLibrary;

    /**
     * Initialize the libraries for the users
     *
     * @var class $usersLibrary
     */
    public $languageFile;

    /**
     * The name of this module
     *
     * @var string $moduleName
     */
    public $moduleName;

    /**
     * The name of this component
     *
     * @var string $componentName
     */
    public $componentName;

    /**
     * Initialise the class constructor
     *
     */
    public function __construct()
    {

        // Initialise the params array for get and set methods
        $this->params = array();

        // Set health check vars
        $this->healthCheckName = array(
            "namespace" => __NAMESPACE__,
            "class" => __CLASS__,
            "method" => __METHOD__,
            "trait" => __TRAIT__,
            "file" =>__FILE__,
            "base" => "auth.users.controller",
            "checksum" => "checksum.auth.users.controller",
            "module" => "auth",
            "component" => "users"
        );

    }

    /**
     * Constructor.
     *
     * @param \CodeIgniter\HTTP\RequestInterface $request
     * @param \CodeIgniter\HTTP\ResponseInterface $response
     * @param \Psr\Log\LoggerInterface $logger
     */
    public function initController(\CodeIgniter\HTTP\RequestInterface $request, \CodeIgniter\HTTP\ResponseInterface $response, \Psr\Log\LoggerInterface $logger)
    {

        // Do Not Edit This Line
        parent::initController($request, $response, $logger);

        // Check if session was started already of begin it
        if(!$this->session) {
            // Session Class
            $this->session = \Config\Services::session();
        }

        // Model Class
        $this->usersModel = new \Acme\Core\System\Modules\Auth\Users\Models\UsersModel();

        // Config Class
        $this->usersConfig = $this->usersModel->usersConfig;

        // Library Class
        $this->usersLibrary = $this->usersModel->usersLibrary;

        // Request Class
        $this->usersLibrary->acmeRequest = $this->acmeRequest;

        // Get the browser negotiated language
        $this->usersConfig->config["i18n.negotiated"] = $this->language;

        // Get the user specified language
        $this->usersConfig->config["i18n.locale"] = $this->locale;

        // Get the system language
        $this->usersConfig->config["i18n.system"] = $this->usersConfig->systemConfig["i18n.user.defined"];

        // Add the system configs to the users config array
        if(!isset($this->usersConfig->config["system.config"])) {

            // Only do so if we have some values
            if($this->usersConfig->config["system.config"] == null){

                // include the system configs in the module config
                $this->usersConfig->config["system.config"] = $this->usersConfig->systemConfig;

            }

        }
        // Check if the module requires https
        if(isset($this->usersConfig->config["security.enforce.https"])) {

            // If th emodule requires https, redirect user to a secure location
            if($this->usersConfig->config["security.enforce.https"] == "yes") {

                // This controller is only accessible via HTTPS
                if (!$this->request->isSecure()) {

                    // Redirect the user to this page via HTTPS, and set the StrictTransport-Security
                    // header so the browser will automatically convert all links to this page to HTTPS
                    // for the next year.

                    force_https();

                }

            }

        }

        // Module Name
        $this->moduleName = "Auth";

        // Component Name
        $this->componentName = "Users";

        // Setup the language file
        $this->languageFile = $this->moduleName . "_" . $this->componentName . ".";

        // Get the current user roles
        $this->userRoles = $this->session->get("AcmeUserRoles");

        // Check if the user is authorised to use this component
        if(!$this->usersLibrary->isModuleAllowed($this->userRoles, __NAMESPACE__, __CLASS__, __METHOD__, $this->moduleName, $this->componentName)){

            // Redirect to forbidden page
            redirect(acme_base_url("page/http403/invalid-module"));

        } else {

            // Check if the user is authorised to use this component
            if(!$this->usersLibrary->isComponentAllowed($this->userRoles, __NAMESPACE__, __CLASS__, __METHOD__, $this->moduleName, $this->componentName)){

                // Redirect to forbidden page
                redirect(acme_base_url("page/http403/invalid-component"));

            }

        }

    }

    /**
     * Get the key value
     *
     * @param string $key
     * @return string
     */
    public function __get( $key )
    {

        // Get a library variable
        return $this->params[ $key ];
    }

    /**
     * Set the key value
     *
     * @param string $key
     * @param mixed $value
     * @return bool
     */
    public function __set( $key, $value )
    {

        // Set a library variable
        return $this->params[ $key ] = $value;

    }

    /**
     * If the controller contains a method named _remap(), it will always get called regardless
     * of what the URI contains. It overrides the normal behavior in which the URI determines
     * which method is called, therby giving room to define a custom method routing rules.
     *
     * @param $method
     * @param array ...$params
     * @return mixed
     */
    public function _remap($method, ...$params)
    {

        if( $method == "index" || $method == null || !$method || empty($method)) {

            // Show the default module landing page
            return $this->index();

        }else{

            // Remap the controller to a corresponding method
            $method = 'ACME' . acme_underscore_to_camel($method);

            // Only remap if the controller method exists
            if (method_exists($this, $method)) {
                return $this->$method(...$params);
            }

            // Or else throw an error: 404 page not found exception
            throw \CodeIgniter\Exceptions\PageNotFoundException::forPageNotFound($method);

        }
    }

    /**
     * The main landing page for the module
     */
    public function index()
    {

        // View all Users dashboard
        $this->ACMEDashboard();

    }

    /**
     * View all Users items or specific details
     *
     * @param string $uuid
     */
    public function ACMEView( $uuid = "all")
    {

        // Check if the user is authorised to perform this action
        if(!$this->usersLibrary->isOperationAllowed($this->userRoles, __NAMESPACE__, __CLASS__, __METHOD__, $this->moduleName, $this->componentName, 'READ')){

            // Redirect to forbidden pageyyyy
            redirect(acme_base_url("page/http403/create-not-allowed"));

        }

        // View all Users items
        $this->DoView($uuid, true);

    }

    /**
     * View all Users items or specific details
     *
     * @param string $uuid
     * @param bool $renderDisplay Whether to render the tabular view or return the recordset
     */
    public function DoView( $uuid = "all", $renderDisplay=false)
    {

        // Pre initialise the  ta object to hold the query criteria
        $dataObject = array();

        if( $uuid == "all" || $uuid == "" || empty($uuid) || !$uuid ){

            // Layout file name
            $layout="UsersGetAll";

            // Specify the data type to expect from the database
            $dataObject["returnType"] = "result_array";

        }else{

            // Layout file name
            $layout="UsersViewDetails";

            // Specify the where clause
            $dataObject["where"] = array(
                "uuid" => $uuid
            );

            // Specify the data type to expect from the database
            $dataObject["returnType"] = "row_array";

        }

        // Tell the model that we need summary
        $dataObject["isDashboard"] = false;

        // Attach the method name
        $method = array(__NAMESPACE__, __CLASS__, __METHOD__);

        if( $renderDisplay ) {

            // Render the view
            $this->usersLibrary->renderView($this, $method, $uuid, $layout, $dataObject, false);

        }else{

            // return a record set
            $results = $this->usersModel->ACMEUsersDBRead( $dataObject);

            return $results;

        }
    }


    /**
     * Insert a new Users item
     *
     */
    public function ACMECreateNew()
    {

        // Check if the user is authorised to perform this action
        if(!$this->usersLibrary->isOperationAllowed($this->userRoles, __NAMESPACE__, __CLASS__, __METHOD__, $this->moduleName, $this->componentName, 'INSERT')){

            // Redirect to forbidden page
            redirect(acme_base_url("page/http403/create-not-allowed"));

        }

        // Insert data into the database
        $this->InsertForm();

    }

    /**
     * Insert a new Users item
     *
     */
    public function InsertForm()
    {

        $uuid = null;

        // Layout file name
        $layout="UsersCreateNew";

        // Pre initialise the  ta object to hold the query criteria
        $dataArray = array();

        // Tell the model that we need summary
        $dataArray["isDashboard"] = false;

        // Specify the data type to expect from the database
        $dataArray["returnType"] = "result_array";

        // Attach the method name
        $method = array(__NAMESPACE__, __CLASS__, __METHOD__);

        // Render the view
        $this->usersLibrary->renderView( $this, $method, $uuid, $layout, $dataArray, false);

    }

    /**
     * Insert a new Users item
     *
     * @return mixed
     */
    public function ACMEInsertItem()
    {

        $this->DoInsert(true);

    }

    /**
     * Insert a new Users item
     * 
     * @param bool $renderDisplay
     * @return mixed
     */
    public function DoInsert( $renderDisplay=false )
    {

        // Get the data array object based on the user input
        $dataObject = $this->usersLibrary->getCRUDArray( 'INSERT' );
        
        // Delete data from the database
        $result = $this->usersModel->ACMEUsersDBInsert( $dataObject );

        // Show we proceed and show the records after the operation?
        if($renderDisplay) {

            // Render the list view, also return the message iin the flash data
            $this->ACMEView("all");

        }else{

            // Return the result as an array object for further processing
            return $result;

        }

    }

    /**
     * Display the Users item update form
     *
     * @param string $uuid
     */
    public function ACMEUpdate( $uuid = "")
    {

        // Check if the user is authorised to perform this action
        if(!$this->usersLibrary->isOperationAllowed($this->userRoles, __NAMESPACE__, __CLASS__, __METHOD__, $this->moduleName, $this->componentName, 'UPDATE')){

            // Redirect to forbidden page
            redirect(acme_base_url("page/http403/update-not-allowed"));

        }

        // Get the ID from the Universal Unique ID
        $id = $this->usersModel->ACMEUsersGetIdFromUUID( $uuid );

        // If the id is undefined, the record does not exist
        if( !$id ){

            // Render the list view, also return the message iin the flash data
            $this->ACMEView("all");

            return;

        }

        // Show the record update form
        $this->UpdateForm( $uuid );

    }

    /**
     * Display the Users item update form
     *
     * @param string $uuid
     */
    public function UpdateForm( $uuid = "")
    {

        // Layout file name
        $layout="UsersUpdateExisting";

        // Pre initialise the  ta object to hold the query criteria
        $dataArray = array();

        // Tell the model that we need summary
        $dataArray["isDashboard"] = false;

        // Specify the data type to expect from the database
        $dataArray["returnType"] = "result_array";

        // Attach the method name
        $method = array(__NAMESPACE__, __CLASS__, __METHOD__);

        // Render the view
        $this->usersLibrary->renderView( $this, $method, $uuid, $layout, $dataArray, false);

    }

    /**
     * Update an existing Users item
     *
     * @param string $uuid The record universal unique id o perform the operation
     * @return mixed
     */
    public function ACMEUpdateItem( $uuid )
    {

        $this->DoUpdate($uuid, true);

    }

    /**
     * Update an existing Users item
     *
     * @param string $uuid The record universal unique id o perform the operation
     * @param bool $renderDisplay Should we return the operation result or just render the view
     * @return mixed
     */
    public function DoUpdate( $uuid, $renderDisplay=false )
    {

        $dataObject = array();

        // Specify the where clause
        $dataObject["where"] = array(
            "uuid" => $uuid
        );

        // Get the data array object based on the user input

        $dataObject["data"] = $this->usersLibrary->getCRUDArray( 'UPDATE' );

        $id = $this->usersModel->ACMEUsersGetIdFromUUID( $uuid );

        // Update data in the database
        $result = $this->usersModel->ACMEUsersDBUpdate( $id, $dataObject);

        // Show we proceed and show the records after the operation?
        if($renderDisplay) {

            // Render the list view, also return the message iin the flash data
            $this->ACMEView("all");

        }else{

            // Return the result as an array object for further processing
            return $result;

        }

    }

    /**
     * Insert a new Users item
     *
     */
    public function ACMEDelete( $uuid = "")
    {

        // Check if the user is authorised to perform this action
        if(!$this->usersLibrary->isOperationAllowed($this->userRoles, __NAMESPACE__, __CLASS__, __METHOD__, $this->moduleName, $this->componentName, 'DELETE')){

            // Redirect to forbidden page
            redirect(acme_base_url("page/http403/delete-not-allowed"));
            
        }

        // Get the ID from the Universal Unique ID
        $id = $this->usersModel->ACMEUsersGetIdFromUUID( $uuid );

        // If the id is undefined, the record does not exist
        if( !$id ){

            // Render the list view, also return the message iin the flash data
            $this->ACMEView("all");

            return;

        }

        // Delete data from the database
        return $this->DoDelete( $id, true );

    }

    /**
     * Delete an existing Users item
     *
     * @param int $id The record id o perform the operation
     * @param bool $renderDisplay Should we return the operation result or just render the view
     * @return  mixed
     */
    public function DoDelete( $id, $renderDisplay=false )
    {

        // Delete data from the database
        $result = $this->usersModel->ACMEUsersDBDelete( $id, array());
        
        // Show we proceed and show the records after the operation?
        if($renderDisplay) {

            // Render the list view, also return the message iin the flash data
            $this->ACMEView("all");

        }else{

            // Return the result as an array object for further processing
            return $result;

        }

    }

    /**
     * Display the Users Dashboard
     */
    public function ACMEDashboard()
    {

        $uuid = null;

        // Layout file name
        $layout="UsersDashboard";

        // Pre initialise the  ta object to hold the query criteria
        $dataArray = array();

        // Tell the model that we need summary
        $dataArray["isDashboard"] = true;

        // Specify the data type to expect from the database
        $dataArray["returnType"] = "result_array";

        // Attach the method name
        $method = array(__NAMESPACE__, __CLASS__, __METHOD__);

        // Render the view
        $this->usersLibrary->renderView( $this, $method, $uuid, $layout, $dataArray);

    }

    /**
     * Test arguments passed
     *
     * @param string $arg
     * @param array ...$params
     */
    public function ACME_args($arg=null, ...$params){

        if(count($params) > 2){

            array_splice($params, count($params) - 2, 2);

        }

        $params1 = $arg;

        $params2 = $params;

        var_dump($params1);

        var_dump($params2);

    }

} 